default:
  image: node:18.17.1

build:
  stage: test
  except:
    - main
  script:
    - npm install --legacy-peer-deps

test:
  stage: build
  only:
    - main
  script:
    - npm install --legacy-peer-deps