default:
  image: node:18.17.1

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

before_script:
  - npm install --legacy-peer-deps

build_job:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

deploy_job:
  stage: deploy
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
  dependencies:
    - build_job
  only:
    - main
  environment:
    name: staging
    url: http://staging.neticops.com
