default:
  image: node:18.17.1


stages:
  - build
  - test
  - deploy


test:
  stage: build
  only:
    - main
  script:
    - npm install --legacy-peer-deps && npm run build && npm install -g serve && serve -s build 